#!/usr/bin/env bash
# =============================================================================
# Diyar OS Installer — Chroot Setup Functions
# core/chroot_setup.sh  —  sourced by engine.sh
#
# Every function here runs operations INSIDE /target via chroot.
# The bind-mounts (proc/sys/dev) are done by engine.sh before calling these.
# =============================================================================

# Convenience wrapper
in_chroot() {
    chroot "${TARGET}" /bin/bash -c "$*" >> "$LOG_FILE" 2>&1
}

# ---------------------------------------------------------------------------
# Hostname
# ---------------------------------------------------------------------------
chroot_set_hostname() {
    local hostname="$1"
    log_info "Setting hostname: ${hostname}"
    echo "${hostname}" > "${TARGET}/etc/hostname"
    # Update /etc/hosts
    cat > "${TARGET}/etc/hosts" <<EOF
127.0.0.1   localhost
127.0.1.1   ${hostname}

::1         localhost ip6-localhost ip6-loopback
ff02::1     ip6-allnodes
ff02::2     ip6-allrouters
EOF
}

# ---------------------------------------------------------------------------
# Locale
# ---------------------------------------------------------------------------
chroot_set_locale() {
    local locale="$1"
    log_info "Setting locale: ${locale}"

    # Enable the locale in locale.gen
    if [[ -f "${TARGET}/etc/locale.gen" ]]; then
        sed -i "s/^# *${locale}/${locale}/" "${TARGET}/etc/locale.gen"
    else
        echo "${locale} UTF-8" > "${TARGET}/etc/locale.gen"
    fi
    # Always ensure en_US.UTF-8 is available as fallback
    sed -i 's/^# *en_US.UTF-8/en_US.UTF-8/' "${TARGET}/etc/locale.gen" \
        || echo "en_US.UTF-8 UTF-8" >> "${TARGET}/etc/locale.gen"

    in_chroot "locale-gen"

    # Set system-wide default
    cat > "${TARGET}/etc/default/locale" <<EOF
LANG=${locale}
LC_MESSAGES=en_US.UTF-8
LC_TIME=${locale}
LC_NUMERIC=${locale}
EOF
}

# ---------------------------------------------------------------------------
# Timezone
# ---------------------------------------------------------------------------
chroot_set_timezone() {
    local tz="$1"
    log_info "Setting timezone: ${tz}"
    ln -sf "/usr/share/zoneinfo/${tz}" "${TARGET}/etc/localtime"
    echo "${tz}" > "${TARGET}/etc/timezone"
    in_chroot "dpkg-reconfigure -f noninteractive tzdata"
}

# ---------------------------------------------------------------------------
# fstab — UUID-based, critical for reliable boot
# This is where most DIY installers fail: they use /dev/sdX paths
# which break when disks are renamed on next boot.
# We ALWAYS use UUIDs.
# ---------------------------------------------------------------------------
chroot_write_fstab() {
    log_info "Writing UUID-based fstab..."

    local root_uuid
    root_uuid="$(get_uuid "${TARGET_PART_ROOT}")"
    [[ -z "$root_uuid" ]] && die "Cannot get UUID for root partition ${TARGET_PART_ROOT}"

    local root_fstype
    root_fstype="$(get_fstype "${TARGET_PART_ROOT}")"

    log_info "Root UUID: ${root_uuid}, fstype: ${root_fstype}"

    cat > "${TARGET}/etc/fstab" <<EOF
# /etc/fstab — Diyar OS
# Generated by diyar-installer on $(date -u '+%Y-%m-%d %H:%M UTC')
# <file system>                           <mount>  <type>    <options>          <dump> <pass>

UUID=${root_uuid}   /        ${root_fstype}   errors=remount-ro  0      1
tmpfs                                   /tmp     tmpfs     defaults,nosuid,nodev 0      0
EOF

    # EFI partition
    if [[ "${FIRMWARE_TYPE:-bios}" == "uefi" ]] && [[ -n "${TARGET_PART_EFI:-}" ]]; then
        local efi_uuid
        efi_uuid="$(get_uuid "${TARGET_PART_EFI}")"
        log_info "EFI UUID: ${efi_uuid}"
        echo "UUID=${efi_uuid}   /boot/efi  vfat    umask=0077         0      2" \
            >> "${TARGET}/etc/fstab"
    fi

    # Swap partition
    if [[ -n "${TARGET_PART_SWAP:-}" ]]; then
        local swap_uuid
        swap_uuid="$(get_uuid "${TARGET_PART_SWAP}")"
        log_info "Swap UUID: ${swap_uuid}"
        echo "UUID=${swap_uuid}   none     swap    sw                 0      0" \
            >> "${TARGET}/etc/fstab"
    fi

    log_info "fstab written:"
    cat "${TARGET}/etc/fstab" >> "$LOG_FILE"
}

# ---------------------------------------------------------------------------
# User account
# ---------------------------------------------------------------------------
chroot_create_user() {
    local username="$1"
    local password="$2"
    local fullname="${3:-}"

    log_info "Creating user: ${username}"

    # Remove live user if present
    in_chroot "id user 2>/dev/null && userdel -r user 2>/dev/null || true"
    in_chroot "id live 2>/dev/null && userdel -r live 2>/dev/null || true"
    in_chroot "id diyar 2>/dev/null && userdel -r diyar 2>/dev/null || true"

    # Create new user
    in_chroot "useradd -m -s /bin/bash \
        -G sudo,audio,video,plugdev,netdev,bluetooth,lpadmin \
        ${fullname:+-c \"${fullname}\"} \
        '${username}'"

    # Set password (hash it safely)
    local hashed
    hashed="$(openssl passwd -6 "${password}")"
    in_chroot "usermod -p '${hashed}' '${username}'"

    # Disable root password login (security)
    in_chroot "passwd -l root"

    # Set up sudo without password for initial setup (user can change later)
    echo "${username} ALL=(ALL) ALL" > "${TARGET}/etc/sudoers.d/diyar-user"
    chmod 440 "${TARGET}/etc/sudoers.d/diyar-user"

    log_info "User '${username}' created."
}

# ---------------------------------------------------------------------------
# Remove live-boot specific packages from installed system
# ---------------------------------------------------------------------------
chroot_remove_live_packages() {
    log_info "Removing live-boot packages..."

    local LIVE_PKGS=(
        live-boot
        live-boot-initramfs-tools
        live-config
        live-config-sysvinit
        live-tools
        # Installer itself
        diyar-installer
    )

    for pkg in "${LIVE_PKGS[@]}"; do
        in_chroot "dpkg -l '${pkg}' 2>/dev/null | grep -q '^ii' && \
            DEBIAN_FRONTEND=noninteractive apt-get remove -y --purge '${pkg}' 2>/dev/null \
            || true"
    done

    # Clean apt cache to save space
    in_chroot "apt-get autoremove -y --purge 2>/dev/null || true"
    in_chroot "apt-get clean 2>/dev/null || true"

    # Rebuild initramfs without live-boot hooks
    in_chroot "update-initramfs -u -k all"

    log_info "Live packages removed."
}

# ---------------------------------------------------------------------------
# GRUB bootloader — BIOS and UEFI
# This is the other place where DIY installers commonly fail.
# Key: always use --target explicitly, always run update-grub AFTER grub-install
# ---------------------------------------------------------------------------
chroot_install_grub() {
    log_info "Installing GRUB bootloader..."
    log_info "Firmware: ${FIRMWARE_TYPE}, Disk: ${TARGET_DISK}"

    if [[ "${FIRMWARE_TYPE}" == "uefi" ]]; then
        # UEFI install
        log_info "Installing grub-efi-amd64..."

        # Ensure grub-efi package is present in target
        in_chroot "dpkg -l grub-efi-amd64 2>/dev/null | grep -q '^ii' || \
            DEBIAN_FRONTEND=noninteractive apt-get install -y grub-efi-amd64"

        in_chroot "grub-install \
            --target=x86_64-efi \
            --efi-directory=/boot/efi \
            --bootloader-id=DiyarOS \
            --recheck \
            --no-floppy"

        # Also install to removable media path for maximum compatibility
        in_chroot "grub-install \
            --target=x86_64-efi \
            --efi-directory=/boot/efi \
            --bootloader-id=DiyarOS \
            --removable \
            --recheck \
            --no-floppy" || true

    else
        # BIOS/Legacy MBR install
        log_info "Installing grub-pc (BIOS)..."

        in_chroot "dpkg -l grub-pc 2>/dev/null | grep -q '^ii' || \
            DEBIAN_FRONTEND=noninteractive apt-get install -y grub-pc"

        in_chroot "grub-install \
            --target=i386-pc \
            --recheck \
            --no-floppy \
            '${TARGET_DISK}'"
    fi

    # Update GRUB config — this reads /etc/default/grub and detects kernels
    log_info "Running update-grub..."
    in_chroot "update-grub"

    # Verify grub.cfg was created
    if [[ ! -f "${TARGET}/boot/grub/grub.cfg" ]]; then
        die "grub.cfg not found after update-grub — bootloader install failed"
    fi

    log_info "GRUB installed successfully."
    grep "menuentry" "${TARGET}/boot/grub/grub.cfg" | head -5 >> "$LOG_FILE" || true
}
