#!/bin/sh
# =============================================================================
# Diyar OS — live-build master configuration
# auto/config
# =============================================================================
set -e

lb config noauto \
    --architectures          amd64 \
    --distribution           bookworm \
    --archive-areas          "main contrib non-free non-free-firmware" \
    --binary-images          iso-hybrid \
    --iso-application        "Diyar OS" \
    --iso-publisher          "Diyar OS Project" \
    --iso-volume             "DIYAR_OS_1_0" \
    --bootappend-live        "boot=live components quiet splash locales=ar_IQ.UTF-8 keyboard-layouts=ara,us timezone=Asia/Baghdad hostname=diyar-live username=diyar" \
    --linux-packages         "linux-image linux-headers" \
    --linux-flavours         amd64 \
    --mirror-bootstrap       "https://deb.debian.org/debian/" \
    --mirror-chroot          "https://deb.debian.org/debian/" \
    --mirror-binary          "https://deb.debian.org/debian/" \
    --mirror-chroot-security "https://security.debian.org/debian-security/" \
    --mirror-binary-security "https://security.debian.org/debian-security/" \
    --apt                    apt \
    --apt-options            "--yes --no-install-recommends" \
    --apt-recommends         false \
    --compression            xz \
    --chroot-filesystem      squashfs \
    --debootstrap-options    "--keyring=/usr/share/keyrings/debian-archive-keyring.gpg" \
    "${@}"
